### ISSUE TITLE
Epub version?

### ISSUE THREAD

**Issue by aqeeliz** [hamdido/quranebook#1]
Hey,

Any plans to include compiled, epub version, for those who don't just want the epub, but don't want to compile it themselves?

Regards,

**Comment by hamdido** [comment]
Please check the Wiki page with some examples: https://github.com/hamdido/quranebook/wiki
Let me know if you need specific translation or format.

**Comment by aqeeliz** [comment]
Thanks.
Didn't look in the wiki.
